In [2]:
import pandas as pd

df = pd.read_csv("/Users/gongwenkai/Projects/Portfolio/Inventory-Health-Analysis/01_Raw_Data/supply_chain_dataset1.csv")
df = pd.read_csv(file_path)

# 查看前 5 行
print("前 5 行数据：")
display(df.head())

# 查看数据规模
print("数据规模：")
print(df.shape)

# 查看字段名
print("字段名：")
print(df.columns.tolist())

# 查看字段类型和非空数量
print("字段类型与非空情况：")
df.info()

# 查看每列缺失值数量
print("每列缺失值数量：")
print(df.isna().sum())

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gongwenkai/Projects/Portfolio/Inventory-Health-Analysis/03_Python/基础\\ SKU\\ Health\\ Analysis.ipynb'

In [3]:
# 查看所有字段名
print(df.columns.tolist())

# 查看前几行，结合字段名理解每列含义
display(df.head())

# 分开查看数值型字段和非数值型字段
numeric_cols = df.select_dtypes(include="number").columns.tolist()
non_numeric_cols = df.select_dtypes(exclude="number").columns.tolist()

print("数值型字段：")
print(numeric_cols)

print("非数值型字段：")
print(non_numeric_cols)

# 查看非数值字段的唯一值数量，帮助判断它是不是类别字段
print("非数值字段的唯一值数量：")
print(df[non_numeric_cols].nunique().sort_values())

['Date', 'SKU_ID', 'Warehouse_ID', 'Supplier_ID', 'Region', 'Units_Sold', 'Inventory_Level', 'Supplier_Lead_Time_Days', 'Reorder_Point', 'Order_Quantity', 'Unit_Cost', 'Unit_Price', 'Promotion_Flag', 'Stockout_Flag', 'Demand_Forecast']

,Date,SKU_ID,Warehouse_ID,Supplier_ID,Region,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,13.95,20.48,0,0,8.52
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,13.95,20.48,0,0,18.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,13.95,20.48,1,0,39.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,13.95,20.48,0,0,19.43
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,13.95,20.48,0,0,18.70

数值型字段：
['Units_Sold', 'Inventory_Level', 'Supplier_Lead_Time_Days', 'Reorder_Point', 'Order_Quantity', 'Unit_Cost', 'Unit_Price', 'Promotion_Flag', 'Stockout_Flag', 'Demand_Forecast']
非数值型字段：
['Date', 'SKU_ID', 'Warehouse_ID', 'Supplier_ID', 'Region']
非数值字段的唯一值数量：
Region            4
Warehouse_ID      5
Supplier_ID      10
SKU_ID           50
Date            365
dtype: int64

In [6]:
# 1. 检查缺失值
print("缺失值数量：")
print(df.isna().sum())

# 2. 检查重复行
print("重复行数量：")
print(df.duplicated().sum())

# 3. 把 Date 转换为日期格式
df["Date"] = pd.to_datetime(df["Date"])

print("日期范围：")
print(df["Date"].min(), df["Date"].max())

# 4. 查看数值字段的基本统计
display(df.describe())

# 5. 检查 0/1 标记字段是否合法
print("Promotion_Flag 取值：")
print(df["Promotion_Flag"].value_counts(dropna=False))

print("Stockout_Flag 取值：")
print(df["Stockout_Flag"].value_counts(dropna=False))

缺失值数量：
Date                       0
SKU_ID                     0
Warehouse_ID               0
Supplier_ID                0
Region                     0
Units_Sold                 0
Inventory_Level            0
Supplier_Lead_Time_Days    0
Reorder_Point              0
Order_Quantity             0
Unit_Cost                  0
Unit_Price                 0
Promotion_Flag             0
Stockout_Flag              0
Demand_Forecast            0
dtype: int64
重复行数量：
0
日期范围：
2024-01-01 00:00:00 2024-12-30 00:00:00

,Date,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
count,91250,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.0,91250.000000
mean,2024-07-01 00:00:00,20.054564,471.522312,7.984000,300.068000,19.272493,12.203320,18.261800,0.101589,0.0,20.082033
min,2024-01-01 00:00:00,0.000000,168.000000,2.000000,201.000000,0.000000,5.020000,6.950000,0.000000,0.0,0.000000
25%,2024-04-01 00:00:00,13.000000,370.000000,4.000000,252.000000,0.000000,8.180000,12.000000,0.000000,0.0,12.950000
50%,2024-07-01 00:00:00,20.000000,461.000000,8.000000,300.000000,0.000000,11.990000,18.180000,0.000000,0.0,19.950000
75%,2024-09-30 00:00:00,27.000000,564.000000,11.000000,346.000000,0.000000,16.320000,23.390000,0.000000,0.0,26.930000
max,2024-12-30 00:00:00,59.000000,990.000000,14.000000,398.000000,499.000000,19.760000,35.100000,1.000000,0.0,61.420000
std,NaN,9.068602,133.488002,3.907929,54.879945,82.340831,4.574982,7.121136,0.302109,0.0,9.503955

Promotion_Flag 取值：
Promotion_Flag
0    81980
1     9270
Name: count, dtype: int64
Stockout_Flag 取值：
Stockout_Flag
0    91250
Name: count, dtype: int64

In [7]:
# 先创建几个基础业务指标
df["Revenue"] = df["Units_Sold"] * df["Unit_Price"]
df["Inventory_Gap"] = df["Inventory_Level"] - df["Reorder_Point"]
df["Forecast_Gap"] = df["Inventory_Level"] - df["Demand_Forecast"]
df["Gross_Margin_Per_Unit"] = df["Unit_Price"] - df["Unit_Cost"]

# 查看新字段
display(df[[
    "SKU_ID",
    "Date",
    "Units_Sold",
    "Inventory_Level",
    "Reorder_Point",
    "Demand_Forecast",
    "Revenue",
    "Inventory_Gap",
    "Forecast_Gap",
    "Gross_Margin_Per_Unit"
]].head())

,SKU_ID,Date,Units_Sold,Inventory_Level,Reorder_Point,Demand_Forecast,Revenue,Inventory_Gap,Forecast_Gap,Gross_Margin_Per_Unit
0,SKU_1,2024-01-01,10,592,379,8.52,204.80,213,583.48,6.53
1,SKU_1,2024-01-02,17,575,379,18.63,348.16,196,556.37,6.53
2,SKU_1,2024-01-03,35,540,379,39.62,716.80,161,500.38,6.53
3,SKU_1,2024-01-04,24,516,379,19.43,491.52,137,496.57,6.53
4,SKU_1,2024-01-05,21,495,379,18.70,430.08,116,476.30,6.53

In [8]:
sku_summary = df.groupby("SKU_ID").agg(
    Total_Units_Sold=("Units_Sold", "sum"),
    Total_Revenue=("Revenue", "sum"),
    Avg_Inventory=("Inventory_Level", "mean"),
    Avg_Reorder_Point=("Reorder_Point", "mean"),
    Avg_Inventory_Gap=("Inventory_Gap", "mean"),
    Avg_Forecast_Gap=("Forecast_Gap", "mean"),
    Avg_Lead_Time=("Supplier_Lead_Time_Days", "mean"),
    Avg_Unit_Cost=("Unit_Cost", "mean"),
    Avg_Unit_Price=("Unit_Price", "mean"),
    Avg_Gross_Margin_Per_Unit=("Gross_Margin_Per_Unit", "mean"),
    Promotion_Days=("Promotion_Flag", "sum"),
    Stockout_Days=("Stockout_Flag", "sum")
).reset_index()

display(sku_summary.head())

,SKU_ID,Total_Units_Sold,Total_Revenue,Avg_Inventory,Avg_Reorder_Point,Avg_Inventory_Gap,Avg_Forecast_Gap,Avg_Lead_Time,Avg_Unit_Cost,Avg_Unit_Price,Avg_Gross_Margin_Per_Unit,Promotion_Days,Stockout_Days
0,SKU_1,37026,617298.40,514.681644,342.8,171.881644,494.402575,8.2,11.562,16.664,5.102,184,0
1,SKU_10,36579,725581.39,459.178082,292.6,166.578082,439.105584,10.2,13.774,19.842,6.068,199,0
2,SKU_11,36358,888870.07,500.064658,317.8,182.264658,480.095825,5.2,15.288,24.456,9.168,191,0
3,SKU_12,36794,582012.28,466.360548,295.8,170.560548,446.203995,7.0,11.762,15.820,4.058,190,0
4,SKU_13,36915,720991.94,485.848219,306.8,179.048219,465.599529,10.2,14.398,19.478,5.080,175,0

In [9]:
def classify_sku(row):
    if row["Avg_Forecast_Gap"] < 0:
        return "Risk"
    elif row["Avg_Inventory_Gap"] < 50:
        return "Watch"
    elif row["Avg_Lead_Time"] > 10:
        return "Watch"
    else:
        return "Healthy"

sku_summary["Health_Status"] = sku_summary.apply(classify_sku, axis=1)

display(sku_summary[[
    "SKU_ID",
    "Total_Units_Sold",
    "Total_Revenue",
    "Avg_Inventory_Gap",
    "Avg_Forecast_Gap",
    "Avg_Lead_Time",
    "Health_Status"
]].head())

,SKU_ID,Total_Units_Sold,Total_Revenue,Avg_Inventory_Gap,Avg_Forecast_Gap,Avg_Lead_Time,Health_Status
0,SKU_1,37026,617298.40,171.881644,494.402575,8.2,Healthy
1,SKU_10,36579,725581.39,166.578082,439.105584,10.2,Watch
2,SKU_11,36358,888870.07,182.264658,480.095825,5.2,Healthy
3,SKU_12,36794,582012.28,170.560548,446.203995,7.0,Healthy
4,SKU_13,36915,720991.94,179.048219,465.599529,10.2,Watch

In [10]:
# 1. 统计不同健康状态的 SKU 数量
print("SKU 健康状态数量：")
print(sku_summary["Health_Status"].value_counts())

# 2. 查看 Watch / Risk SKU
attention_skus = sku_summary[
    sku_summary["Health_Status"].isin(["Watch", "Risk"])
].copy()

# 3. 按收入从高到低排序，优先关注业务影响大的 SKU
attention_skus = attention_skus.sort_values(
    by="Total_Revenue",
    ascending=False
)

display(attention_skus[[
    "SKU_ID",
    "Health_Status",
    "Total_Units_Sold",
    "Total_Revenue",
    "Avg_Inventory_Gap",
    "Avg_Forecast_Gap",
    "Avg_Lead_Time",
    "Stockout_Days"
]].head(10))

SKU 健康状态数量：
Health_Status
Healthy    40
Watch      10
Name: count, dtype: int64

,SKU_ID,Health_Status,Total_Units_Sold,Total_Revenue,Avg_Inventory_Gap,Avg_Forecast_Gap,Avg_Lead_Time,Stockout_Days
31,SKU_38,Watch,36739,1057641.51,174.563288,457.183868,11.2,0
33,SKU_4,Watch,36811,770679.65,172.573151,450.401260,10.2,0
11,SKU_2,Watch,36490,746765.46,175.115068,451.289589,10.2,0
1,SKU_10,Watch,36579,725581.39,166.578082,439.105584,10.2,0
4,SKU_13,Watch,36915,720991.94,179.048219,465.599529,10.2,0
22,SKU_3,Watch,36785,668701.09,170.209315,423.318290,10.6,0
37,SKU_43,Watch,36535,646114.55,171.785205,478.068997,10.4,0
29,SKU_36,Watch,36594,604862.63,171.132055,445.590099,11.4,0
49,SKU_9,Watch,36855,593421.66,164.889863,467.348159,10.6,0
35,SKU_41,Watch,36532,525021.08,175.970411,503.912110,11.2,0

In [11]:
total_skus = sku_summary["SKU_ID"].nunique()
health_counts = sku_summary["Health_Status"].value_counts()

watch_count = health_counts.get("Watch", 0)
risk_count = health_counts.get("Risk", 0)
healthy_count = health_counts.get("Healthy", 0)

watch_ratio = watch_count / total_skus
risk_ratio = risk_count / total_skus

top_watch_skus = attention_skus.head(5)

print("SKU 总数:", total_skus)
print("Healthy 数量:", healthy_count)
print("Watch 数量:", watch_count)
print("Risk 数量:", risk_count)
print("Watch 占比:", round(watch_ratio, 2))
print("Risk 占比:", round(risk_ratio, 2))

display(top_watch_skus[[
    "SKU_ID",
    "Total_Revenue",
    "Avg_Lead_Time",
    "Avg_Inventory_Gap",
    "Avg_Forecast_Gap"
]])

SKU 总数: 50
Healthy 数量: 40
Watch 数量: 10
Risk 数量: 0
Watch 占比: 0.2
Risk 占比: 0.0

    SKU_ID  Total_Revenue  Avg_Lead_Time  Avg_Inventory_Gap  Avg_Forecast_Gap
31  SKU_38     1057641.51           11.2         174.563288        457.183868
33   SKU_4      770679.65           10.2         172.573151        450.401260
11   SKU_2      746765.46           10.2         175.115068        451.289589
1   SKU_10      725581.39           10.2         166.578082        439.105584
4   SKU_13      720991.94           10.2         179.048219        465.599529